name: wave_share
description: "Peer-to-peer water sports equipment rental platform"
publish_to: 'none'
version: 1.0.1

environment:
  sdk:  '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  
  # State Management
  provider: ^6.1.5
  
  # Navigation
  go_router: ^17.1.0
  
  # Maps & Location (comment out for now if you want)
  # google_maps_flutter: ^2.5.3
  # geolocator: ^10.1.0
  # geocoding: ^2.1.1
  
  # Images
  image_picker: ^1.2.1
  
  # Calendar
  table_calendar: ^3.2.0
  
  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4

  # Confetti (NEW)
  confetti: ^0.8.0

  # Firebase (NEW)
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_storage: ^13.0.6
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.1.0

  device_preview: ^1.3.1 

  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter:
  uses-material-design: true

  assets: 
    - lib/assets/images/paddologo.png
    - lib/assets/images/fishingkayak.jpeg
    - lib/assets/images/beginnersup.webp
    - lib/assets/images/jetski.jpg
    - lib/assets/images/PaddleBoard.webp
    - lib/assets/images/singlekayak.jpeg
    - lib/assets/images/tandemkayak.webp

  fonts:
    - family: GlacialIndifference
      fonts:
        - asset: lib/assets/fonts/GlacialIndifference-Regular.otf
        - asset: lib/assets/fonts/GlacialIndifference-Bold.otf
          weight: 700  

